"""Phase 2 AI and Deduplication

Revision ID: 3c94832a8fd3
Revises: 
Create Date: 2026-09-19 12:07:04.770019+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c94832a8fd3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reporter_info', sa.Text(), nullable=True),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('Fire', 'Flood', 'Medical', 'Accident', 'Other')", name='ck_incidents_category'),
    sa.CheckConstraint("severity IN ('High', 'Medium', 'Low')", name='ck_incidents_severity'),
    sa.CheckConstraint("status IN ('Pending', 'Assigned', 'Resolved')", name='ck_incidents_status'),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='ck_incidents_latitude_range'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='ck_incidents_longitude_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_category'), 'incidents', ['category'], unique=False)
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index('ix_incidents_lat_lon', 'incidents', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index('ix_incidents_status_severity', 'incidents', ['status', 'severity'], unique=False)
    op.create_index(op.f('ix_incidents_title'), 'incidents', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_title'), table_name='incidents')
    op.drop_index('ix_incidents_status_severity', table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index('ix_incidents_lat_lon', table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_category'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
